textbox = noone;


nophtext[0] = "WHERE AM I? WHAT HAPPENED? LAST THING I REMEMBER IS...";
nophtext[1] = "...MY BATTLE AGAINST NAJ...!";
nophtext[2] = "DID I...PERISH?";
nophtext[3] = "HMMM...I STILL FEEL MY BODY...";
nophtext[4] = "...DEFINETLY SOMEWHAT ALIVE STILL. DID THAT SACK OF COSMIC DUST IMPRISON ME?";
nophtext[5] = "TO THINK THAT I, NOPHITE, THE COSMIC SCOURGE, HARBINGER OF DECAY, THE GREAT PLAGUEWEAVER WOULD BE DEFEATED BY HER... ";
nophtext[6] = "PERHAPS I UNDERESTIMATED HER... ";
nophtext[7] = "NONSENSE...I AM NEVER WRONG. LET'S LEAVE WHATEVER THIS DIMENSION IS AND LURE HER OUT FOR ROUND 2! ";
nophtext[8] = "I SHOULD START BY LURING OUT HER UNDERLINGS...STARTING WITH TERANAXX...	HE SHOULD BE EASY. ";
nophtext[9] = "BUT FIRST...I SHALL FREE MYSELF OF THIS SAD EXCUSE OF A PRISON. ";
nophtext[10] = "NONE CAN IMPRISON NOPHITE VAN VYLAANIR!";
nophtext[11] = "NOW...TIME TO WREAK SOME HAVOC!";
nophtext[12] = " ";
