textbox = noone;


nophtext[0] = "YOU WRETCHED BEAST, HOW DARE YOU!";
nophtext[1] = "OH MY IT APPEARS THAT YOU ARE OUT OF ARMS...WHAT A SHAME. ";
nophtext[2] = "LADY NAJ WILL HEAR OF THIS, MARK MY WORDS NOPHITE!";
nophtext[3] = "YES YES, SURE...NOW LET ME EXAMINE THIS NEWLY ACQUIRED DOMAIN.";
nophtext[4] = "YOU ARE NOTHING BUT A DISEASE TO THIS UNIVERSE...";
nophtext[5] = "...AND WE WILL NOT STAND IDLY BY WHILE YOU WREAK HAVOC UPON OUR DOMAINS.";
nophtext[6] = "WE? DO YOU TALK ABOUT Y'LINAASH? AS IF THAT THING WOULD LEND YOU ITS AID. ";
nophtext[7] = "JUST YOU WAIT, PLAGUEWEAVER! ";
nophtext[8] = " "
