audio_stop_all();
textbox = noone;


nophtext[0] = "OH LOOK, THE 'MIGHTY' TERANAXX CRAWLED OUT OF HIS POCKET DIMENSION...";
nophtext[1] = "NOPHITE, YOU INVADE MY DOMAIN, SLAUGHTER MY FELLOW CRUSADERS AND NOW YOU HAVE THE AUDACITY TO TAUNT ME?!";
nophtext[2] = "'YOUR' DOMAIN, THE DOMAIN NAJ PROVIDED TO YOU...AND THE DOMAIN I SHALL TAKE AS THE STRONGEST OF US THREE!";
nophtext[3] = "IS THAT YOUR INTENTION? IN THAT CASE I WILL HAPPILY BLAST THAT DISGUSTING PARASITE THAT YOU ARE BACK INTO OBLIVION!";
nophtext[4] = "IF THAT IS HOW YOU'D LIKE TO SETTLE THIS.";
nophtext[5] = "THEN COME AT ME YOU LUNATIC!";
nophtext[6] = " ";
